---
functions:
  - name: install
    description: install the host collector on a managed host
    export: true
    run:
      - sh -c './install.sh'

  - name: uninstall
    description: uninstall the host collector from a managed host
    export: true
    run:
      - sh -c './uninstall.sh'

  - name: start
    description: start the Host Collector service
    export: true
    run:
      - sh -c 'sudo systemctl enable --now telemetry'

  - name: stop
    description: stop the Host Collector service
    export: true
    run:
      - sh -c 'sudo systemctl stop telemetry'      